import React, { useState, useEffect } from "react";
import {
  Bell, AlertTriangle, CheckCircle2, ShieldAlert, Check, X,
  Search, Filter, Clock, RefreshCw, LifeBuoy
} from "lucide-react";
import { alertService, mineService } from "../services/api";
import WorkersInDangerSection from "../components/WorkersInDangerSection";

export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [mines, setMines] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [severityFilter, setSeverityFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [mineFilter, setMineFilter] = useState("");

  const fetchData = () => {
    setLoading(true);
    Promise.all([
      alertService.getAll({
        severity: severityFilter || undefined,
        status: statusFilter || undefined,
        mine_id: mineFilter || undefined
      }),
      mineService.getAll({ limit: 50 })
    ])
      .then(([aRes, mRes]) => {
        setAlerts(aRes.data);
        setMines(mRes.data);
      })
      .catch((err) => console.error(err))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchData();
  }, [severityFilter, statusFilter, mineFilter]);

  const handleAcknowledge = async (id) => {
    try {
      await alertService.acknowledge(id);
      fetchData();
    } catch {
      alert("Failed to acknowledge alert.");
    }
  };

  const handleResolve = async (id) => {
    try {
      await alertService.resolve(id);
      fetchData();
    } catch {
      alert("Failed to resolve alert.");
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="gov-card p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Bell className="w-5 h-5 text-[#DC2626]" />
            <h1 className="page-title text-xl sm:text-2xl font-bold text-[#1F2937]">
              Emergency Alerts & Safety Anomaly Center
            </h1>
          </div>
          <p className="text-xs text-[#6B7280] mt-0.5">
            Automated notifications generated by Isolation Forest multi-gas telemetry breaches, active hazards, and worker safety conditions.
          </p>
        </div>

        <button onClick={fetchData} className="btn-secondary text-xs">
          <RefreshCw className="w-3.5 h-3.5" />
          <span>Refresh Alerts</span>
        </button>
      </div>

      {/* Prominent Workers in Danger Section */}
      <WorkersInDangerSection onRescueTriggered={fetchData} />

      {/* Filter Toolbar */}
      <div className="gov-card p-4">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div>
            <label className="block text-xs font-semibold text-[#6B7280] mb-1">Severity</label>
            <select
              value={severityFilter}
              onChange={(e) => setSeverityFilter(e.target.value)}
              className="w-full px-2.5 py-1.5 bg-[#F5F7FA] border border-gray-200 rounded-md text-xs text-[#1F2937] focus:outline-none focus:ring-1 focus:ring-[#1E5B3A]"
            >
              <option value="">All Severities</option>
              <option value="CRITICAL">Critical</option>
              <option value="HIGH">High</option>
              <option value="MEDIUM">Medium</option>
              <option value="LOW">Low</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold text-[#6B7280] mb-1">Status</label>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="w-full px-2.5 py-1.5 bg-[#F5F7FA] border border-gray-200 rounded-md text-xs text-[#1F2937] focus:outline-none focus:ring-1 focus:ring-[#1E5B3A]"
            >
              <option value="">All Statuses</option>
              <option value="UNREAD">Unread</option>
              <option value="ACKNOWLEDGED">Acknowledged</option>
              <option value="RESOLVED">Resolved</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold text-[#6B7280] mb-1">Mine</label>
            <select
              value={mineFilter}
              onChange={(e) => setMineFilter(e.target.value)}
              className="w-full px-2.5 py-1.5 bg-[#F5F7FA] border border-gray-200 rounded-md text-xs text-[#1F2937] focus:outline-none focus:ring-1 focus:ring-[#1E5B3A]"
            >
              <option value="">All Mines</option>
              {mines.map((m) => (
                <option key={m.id} value={m.id}>{m.name}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="gov-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left gov-table">
            <thead>
              <tr>
                <th>Severity</th>
                <th>Alert Notification & Message</th>
                <th>Mine</th>
                <th>Timestamp</th>
                <th>Status</th>
                <th className="text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {loading ? (
                <tr>
                  <td colSpan="6" className="py-12 text-center text-xs text-[#6B7280]">
                    Loading statutory telemetry alerts...
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan="6" className="py-12 text-center text-xs text-[#6B7280]">
                    No alerts found for the selected criteria.
                  </td>
                </tr>
              ) : (
                alerts.map((a) => (
                  <tr key={a.id}>
                    <td>
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                          a.severity === "CRITICAL"
                            ? "bg-red-100 text-[#DC2626]"
                            : a.severity === "HIGH"
                            ? "bg-orange-100 text-[#EA580C]"
                            : "bg-amber-100 text-[#D97706]"
                        }`}
                      >
                        {a.severity}
                      </span>
                    </td>
                    <td>
                      <div className="font-semibold text-xs text-[#1F2937]">
                        {a.alert_type || "Safety Anomaly"}
                      </div>
                      <p className="text-xs text-[#4B5563] mt-0.5 max-w-md">
                        {a.message}
                      </p>
                    </td>
                    <td>
                      <span className="font-semibold text-xs text-[#1F2937]">
                        {a.mine?.name}
                      </span>
                    </td>
                    <td className="text-xs text-[#6B7280]">
                      {a.timestamp ? a.timestamp.replace("T", " ").slice(0, 19) : "Recent"}
                    </td>
                    <td>
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          a.status === "RESOLVED"
                            ? "bg-green-100 text-[#15803D]"
                            : a.status === "ACKNOWLEDGED"
                            ? "bg-blue-100 text-[#2563EB]"
                            : "bg-amber-100 text-[#D97706]"
                        }`}
                      >
                        {a.status}
                      </span>
                    </td>
                    <td className="text-right">
                      <div className="flex items-center justify-end gap-1.5">
                        {a.status === "UNREAD" && (
                          <button
                            onClick={() => handleAcknowledge(a.id)}
                            className="px-2 py-1 text-xs font-semibold text-[#1E5B3A] bg-[#1E5B3A]/10 hover:bg-[#1E5B3A]/20 rounded transition"
                          >
                            Acknowledge
                          </button>
                        )}
                        {a.status !== "RESOLVED" && (
                          <button
                            onClick={() => handleResolve(a.id)}
                            className="px-2 py-1 text-xs font-semibold text-white bg-[#15803D] hover:bg-green-800 rounded transition"
                          >
                            Resolve
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
